# Generated by Django 5.2.7 on 2025-10-21 00:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('summary', models.TextField(verbose_name='Resumo')),
                ('content', models.TextField(verbose_name='Conteúdo Completo')),
                ('image', models.ImageField(upload_to='articles/', verbose_name='Imagem de Destaque')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
    ]
