# Generated by Django 5.2.7 on 2025-10-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Alfredo Torres', max_length=100, verbose_name='Autor'),
            preserve_default=False,
        ),
    ]
