# Generated by Django 5.2.7 on 2025-11-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Contagem de Visualizações'),
        ),
    ]
