# Generated by Django 5.2.7 on 2025-11-11 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_article_view_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='feed.article')),
            ],
        ),
    ]
