# Generated by Django 5.2.7 on 2025-12-09 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('thumbnail', models.ImageField(upload_to='flash_videos/', verbose_name='Thumbnail do Vídeo')),
                ('video_url', models.URLField(verbose_name='URL do Vídeo (YouTube, etc.)')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Publicação')),
            ],
            options={
                'verbose_name': 'Vídeo Flash',
                'verbose_name_plural': 'Vídeos Flash',
                'ordering': ['-publication_date'],
            },
        ),
    ]
