# Generated by Django 5.2.7 on 2025-12-09 19:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_flashvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashvideo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Vídeo Flash', 'verbose_name_plural': 'Vídeos Flash'},
        ),
        migrations.RemoveField(
            model_name='flashvideo',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='flashvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flashvideo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='flashvideo',
            name='thumbnail',
            field=models.ImageField(upload_to='flash_videos/', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='flashvideo',
            name='video_url',
            field=models.URLField(verbose_name='URL do Vídeo'),
        ),
    ]
