# Generated by Django 5.2.7 on 2025-12-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_alter_flashvideo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashvideo',
            name='video_url',
        ),
        migrations.AddField(
            model_name='flashvideo',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='flash_videos/videos/', verbose_name='Arquivo de Vídeo (.mp4)'),
        ),
        migrations.AlterField(
            model_name='flashvideo',
            name='thumbnail',
            field=models.ImageField(upload_to='flash_videos/thumbnails/', verbose_name='Thumbnail'),
        ),
    ]
